version: '2'
services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=dev_user"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - pgsql-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ".:/"
    tty: true
volumes:
  pgsql-data:
    driver: local

